QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = false -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 10 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 50 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 50 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 50 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 50 } } },

	police = {
        label = 'LSPD',
        type = 'leo',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Constable', payment = 100 },
            ['1'] = { name = 'Sergeant', payment = 250 },
            ['2'] = { name = 'Inspector', payment = 300 },
            ['3'] = { name = 'Chief Inspector', payment = 450 },
            ['4'] = { name = 'Superintendent', payment = 550 },
            ['5'] = { name = 'Chief Superintendant', payment = 650 },
            ['6'] = { name = 'Assistant Chief Constable', payment = 750 },
            ['7'] = { name = 'Deputy Chief Constable', payment = 850 },
            ['8'] = { name = 'Chief Constable', payment = 950, isboss=true },
            ['9'] = { name = 'Commisioner', payment = 1050, isboss=true },
            ['10'] = { name = 'Internal Affairs', payment = 1051, isboss=true },
        },
	},
	ambulance = {
		label = 'NHS',
		type = 'NHS',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Medical Student', payment = 100 },
			['1'] = { name = 'Healthcare Assistant', payment = 250 },
			['2'] = { name = 'Advanced Paramedic', payment = 300 },
			['3'] = { name = 'Senior Paramedic', payment = 450 },
			['4'] = { name = 'Nurse', payment = 550 },
            ['5'] = { name = 'Doctor', payment = 650 },
			['6'] = { name = 'Consultant', payment = 750 },
			['7'] = { name = 'Assistant Chief Medical Officer', payment = 850 },
			['8'] = { name = 'Chief Medical Officer', payment = 950, isboss=true },
			['9'] = { name = 'Commisioner', payment = 1050, isboss=true },
			['10'] = { name = 'Internal Affairs', payment = 1051, isboss=true },
		},
	},
	doj = {
		label = 'DOJ',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Paralegal', payment = 100 },
			['1'] = { name = 'Junior Associates', payment = 250 },
			['2'] = { name = 'Associates', payment = 300 },
			['3'] = { name = 'Lawyer', payment = 450 },
			['4'] = { name = 'Chief Lawyer', payment = 550 },
            ['5'] = { name = 'Assistant District Attorney', payment = 650 },
			['6'] = { name = 'District Attorney', payment = 750 },
			['7'] = { name = 'Judge', payment = 850 },
			['8'] = { name = 'Chief Justice', payment = 950, isboss=true },
			['9'] = { name = 'Commisioner', payment = 1050, isboss=true },
			['10'] = { name = 'Internal Affairs', payment = 1051, isboss=true },
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Manager', payment = 125 },
			['4'] = { name = 'Owner', isboss = true, payment = 150 },
		},
	},
	cluckinbell = {
		label = 'cluckingbell',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Employee', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	hookah = {
	    label = "Hookah Bar",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	puffpuffpass = {
		label = 'Puff Puff Pass',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Employee', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	catcafe = {
	    label = "Cat Cafe",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 55 },
			['2'] = { name = 'Event Driver', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 55 },
			['2'] = { name = 'Business Sales', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	honda = {
		label = 'Motorcycle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 55 },
			['2'] = { name = 'Business Sales', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	exoticautos = {
		label = 'Exotic Auto Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 55 },
			['2'] = { name = 'Business Sales', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	tunerscar = {
		label = 'Tuner Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 55 },
			['2'] = { name = 'Business Sales', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	rustys = {
		label = 'Rustys Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	tuners = {
		label = 'Tuners',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee', payment = 50 },
			['1'] = { name = 'Mechanic', payment = 55 },
			['2'] = { name = 'Lead Mechanic', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	burgershot = {
		label = "Burgershot",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Burger Flipper", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	beanmachine = {
		label = "Bean Machine",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},		
	},
	bennys = {
		label = 'Evos',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },	
		},
	},
	rossys = {
		label = 'Rossys',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },	
		},
	},
	muscledealer = {
		label = 'muscledealer',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
				['0'] = { name = 'Recruit', payment = 50 },
				['1'] = { name = 'Showroom Sales', payment = 55 },
				['2'] = { name = 'Business Sales', payment = 60 },
				['3'] = { name = 'Manager', payment = 65 },
				['4'] = { name = 'Owner', isboss = true, payment = 70 },
			},
		},
	taco = {
		label = "Taco Bar",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		}, 
	},
	treybakery = {
	    label = "Trey Bakery",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Baker", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	mechanic = {
		label = 'mechanic',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	unicorn = {
	    label = "Vanilla Unicorn",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	beachclub = {
	    label = "Beach Club",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	bahamamama = {
	    label = "Bahama Mamas",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	club77 = {
	    label = "Club 77",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	kebabking = {
	    label = "Kebab King",
        defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
            ['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	hornys = {
		label = "Hornys",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Burger Flipper", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	lscustoms = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	autoexotics = {
		label = 'Auto Exotics',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	tequilala = {
		label = "Tequilala",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	pizzathis = {
		label = "Pizza This",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Experienced", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	upnatom = {
		label = "Up N Atom",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Burger Flipper", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},	
	pearls = {
		label = "Pearls",
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = "Trainee", payment = 50 },
			['1'] = { name = "Employee", payment = 55 },
			['2'] = { name = "Team Leader", payment = 60 },
			['3'] = { name = "Manager", payment = 65 },
			['4'] = { name = "Owner", isboss = true, payment = 70 },
		},
	},
	luxury = {
		label = 'Luxury',
		type = 'cardealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
		},
	},
	fishnchips = {
		label = 'Fish N Chips',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
            ['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 55 },
			['2'] = { name = 'Experienced', payment = 60 },
			['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss = true, payment = 70 },
        },
    },
	trestudio = {
		label = 'Tre Studio',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
            ['0'] = { name = 'Recruit', payment = 50 },
            ['1'] = { name = 'Novice', payment = 55 },
            ['2'] = { name = 'Experienced', payment = 60 },
            ['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss= true, payment = 70 },
			
        },
    },
	overspeedsautos = {
		label = 'Overspeed Mechanics',
		type = 'mechanic',
		defaultDuty = false,
		offDutyPay = false,
		grades = {
            ['0'] = { name = 'Recruit', payment = 50 },
            ['1'] = { name = 'Novice', payment = 55 },
            ['2'] = { name = 'Experienced', payment = 60 },
            ['3'] = { name = 'Manager', payment = 65 },
			['4'] = { name = 'Owner', isboss= true, payment = 70 },
			
        },
    },
}
