Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

-- Deliveries
Config.ShopsInvJsonFile = './json/shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'cryptostick'
Config.Fuel = 'cdn-fuel'

Config.DeliveryLocations = {
    -- ['main'] = { label = 'GO Postal', coords = vector4(69.0862, 127.6753, 79.2123, 156.7736) },
    -- ['vehicleWithdraw'] = vector4(71.9318, 120.8389, 79.0823, 160.5110),
    -- ['vehicleDeposit'] = vector3(62.7282, 124.9846, 79.0926),
    -- ['stores'] = {} -- auto generated
}

Config.Vehicles = {
    ['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
    ['normal'] = {
        { name = 'tosti',         price = 25,   amount = 50 },
        { name = 'water_bottle',  price = 25,   amount = 50 },
        { name = 'kurkakola',     price = 25,   amount = 50 },
        { name = 'twerks_candy',  price = 25,   amount = 50 },
        { name = 'snikkel_candy', price = 25,   amount = 50 },
        { name = 'sandwich',      price = 25,   amount = 50 },
        { name = 'beer',          price = 50,   amount = 50 },
        { name = 'whiskey',       price = 50,  amount = 50 },
        { name = 'vodka',         price = 50,  amount = 50 },
        { name = 'bandage',       price = 300, amount = 50 },
        { name = 'lighter',       price = 50,   amount = 50 },
        { name = 'jolly_ranchers', price = 25,   amount = 50 },
        { name = 'ice',       price = 25,   amount = 50 },
        { name = 'bakingsoda',         price = 40, amount = 5000 },
        { name = 'scrunchie',         price = 10, amount = 5000 },
    },
    ['medshop'] = {
        { name = 'bandage',       price = 300, amount = 50 },
    },
    ['liquor'] = {
        { name = 'beer',    price = 7,  amount = 50 },
        { name = 'whiskey', price = 10, amount = 50 },
        { name = 'vodka',   price = 12, amount = 50 },
    },
    ['hardware'] = {
        { name = 'weapon_wrench',     price = 1000, amount = 250 },
        { name = 'screwdriverset',    price = 1000, amount = 50 },
        { name = 'binoculars',        price = 1000,  amount = 50 },
        { name = 'cleaningkit',       price = 1000, amount = 150 },
        { name = 'pickaxe',           price = 1000, amount = 5000 },
        { name = 'fishingrod',        price = 500, amount = 5000 },
        { name = 'fishbait',          price = 100, amount = 5000 },
        { name = 'empty_bottle',      price = 100, amount = 5000 },
        { name = 'syringe',           price = 100, amount = 5000 },
        { name = 'bucket',            price = 100, amount = 5000 },
        { name = 'spraycan',          price = 50000, amount = 5000 },
        { name = 'syphoningkit',      price = 500, amount = 5000 },
        { name = 'plasticwrap',       price = 100, amount = 5000 },
        { name = 'duffle1',           price = 5000, amount = 5000 },
        { name = 'duffle2',           price = 10000, amount = 5000 },
    },
    ['mining'] = {
        { name = 'water_bottle',        price = 10, amount = 100 },
        { name = 'sandwich',            price = 10, amount = 100 },
        { name = 'bandage',             price = 500, amount = 100 },
        { name = 'weapon_flashlight',   price = 2000, amount = 100 },
        { name = 'goldpan',             price = 200,  amount = 100 },
        { name = 'miningdrill',         price = 10000, amount = 100 },
        { name = 'pickaxe',             price = 200, amount = 100,  },
        { name = 'mininglaser',         price = 50000, amount = 100 },
        { name = 'drillbit',            price = 100, amount = 100 },
    },
    ['prison'] = {
        { name = 'sandwich',        price = 25, amount = 50 },
        { name = 'water_bottle',    price = 25, amount = 50 },
        { name = 'weapon_shiv',     price = 500, amount = 50 },
    },
    ['police'] = {
        { name = 'weapon_glock22',      price = 10, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', ['label']= 'Flashlight' } } } },
        { name = 'weapon_stungun',      price = 10, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', ['label']= 'Flashlight' } } } },
        { name = 'weapon_pumpshotgun',  price = 10, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', ['label']= 'Flashlight' } } } },
        { name = 'weapon_smg',          price = 10, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', ['label']= '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', ['label']= 'Flashlight' } } } },
        { name = 'weapon_carbinerifle', price = 10, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', ['label']= 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', ['label']= '3x Scope' } } } },
        { name = 'weapon_nightstick',   price = 10, amount = 50 },
        { name = 'weapon_flashlight',   price = 2, amount = 50 },
        { name = 'pistol_ammo',         price = 1, amount = 50 },
        { name = 'smg_ammo',            price = 1, amount = 50 },
        { name = 'shotgun_ammo',        price = 1, amount = 50 },
        { name = 'rifle_ammo',          price = 1, amount = 50 },
        { name = 'handcuffs',           price = 5, amount = 50 },
        { name = 'empty_evidence_bag',  price = 5, amount = 50 },
        { name = 'police_stormram',     price = 5, amount = 50 },
        { name = 'radio',               price = 2, amount = 50 },
        { name = 'bandage',             price = 2, amount = 50 },
        { name = 'ifaks',               price = 2, amount = 50 },
        { name = 'heavyarmor',          price = 2, amount = 50 },
        { name = 'uvlight',             price = 2, amount = 50 },
        { name = 'defib',               price = 2, amount = 50 },
    },
    ['ambulance'] = {
        { name = 'radio',                   price = 2, amount = 50 },
        { name = 'bandage',                 price = 1, amount = 50 },
        { name = 'painkillers',             price = 1, amount = 50 },
        { name = 'firstaid',                price = 5, amount = 50 },
        { name = 'weapon_flashlight',       price = 2, amount = 50 },
        { name = 'weapon_fireextinguisher', price = 10, amount = 50 },
        { name = 'weapon_stungun',          price = 10, amount = 50 },
        { name = 'heavyarmor',              price = 2, amount = 50 },
        { name = 'medbag',                  price = 5, amount = 50 },
        { name = 'sucker',                  price = 5, amount = 50 },
        { name = 'tweezers',                price = 5, amount = 50 },
        { name = 'suturekit',               price = 5, amount = 50 },
        { name = 'icepack',                 price = 5, amount = 50 },
        { name = 'burncream',               price = 5, amount = 50 },
        { name = 'defib',                   price = 5, amount = 50 },
        { name = 'sedative',                price = 5, amount = 50 },
        { name = 'medikit',                 price = 5, amount = 50 },
    },
    weddingrings  = {
        { name = 'ring1f',         price = 5000, amount = 5000 },
        { name = 'ring2f',         price = 5000, amount = 5000 }, 
        { name = 'ring3f',         price = 5000, amount = 5000 },
        { name = 'ring4f',         price = 5000, amount = 5000 },
        { name = 'ring5f',         price = 5000, amount = 5000 },
        { name = 'ring1m',         price = 5000, amount = 5000 },
        { name = 'ring2m',         price = 5000, amount = 5000 }, 
        { name = 'ring3m',         price = 5000, amount = 5000 },
        { name = 'ring4m',         price = 5000, amount = 5000 },
        { name = 'ring5m',         price = 5000, amount = 5000 },
        { name = 'engagement1',    price = 4000, amount = 5000 },
        { name = 'engagement2',    price = 4000, amount = 5000 },
        { name = 'promisering1',   price = 3000, amount = 5000 },
        { name = 'promisering2',   price = 3000, amount = 5000 },
    },
    puffpuff  = {
        { name = 'wwbrownies',          price = 100, amount = 5000 },
        { name = 'wwgummies',           price = 100, amount = 5000 },
        { name = 'wwcookies',           price = 100, amount = 150 },
        { name = 'wwcupcakes',          price = 100, amount = 150 }, 
        { name = 'wwchocobar',          price = 100, amount = 150 }, 
    },
    weedshop = {
            {name = 'watering_can',         price = 500, amount = 150},
            {name = 'fertilizer',           price = 25, amount = 150},
            {name = 'mini_shovel',          price = 500, amount = 150},
            {name = 'cannabis_seed',        price = 500, amount = 150},
            {name = 'cannabis_seed_female', price = 500, amount = 150},
            {name = 'ocb_paper',            price = 1, amount = 5000 },
            {name = 'emptybaggies',         price = 1, amount = 5000 },
        }
}

Config.Locations = {
    -- Hardware Store Locations
    ['hardware'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(45.68, -1749.04, 29.00, 53.13),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(89.15, -1745.29, 30.09, 315.25)
    },

    ['hardware2'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['hardware3'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },
    ['mining1'] = {
        ['label'] = 'Mining Store',
        ['coords'] = vector4(2956.92, 2753.59, 43.71, 197.57),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Mining Store',
        ['products'] = Config.Products['mining'],
        ['showblip'] = false,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2956.92, 2753.59, 43.71, 197.57)
    },
    ['mining2'] = {
        ['label'] = 'Mining Store',
        ['coords'] = vector4(-594.96, 2091.3, 131.47, 67.65),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Mining Store',
        ['products'] = Config.Products['mining'],
        ['showblip'] = false,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-594.96, 2091.3, 131.47, 67.65)
    },
    ['mining3'] = {
        ['label'] = 'Mining Store',
        ['coords'] = vector4(1074.89, -1988.19, 30.89, 235.07),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Mining Store',
        ['products'] = Config.Products['mining'],
        ['showblip'] = false,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1074.89, -1988.19, 30.89, 235.07)
    },

    -- Weedshop Locations
    ['puffpuff']  = {
        ['label'] = 'Goodies',
        ['coords']  = vector4(-1563.46, -454.49, 35.89, 347),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['puffpuff'],
        ['delivery'] = vector4(-1563.46, -454.49, 35.89, 347),
        ['requiredJob']  = 'puffpuffpass', -- Example: { 'mechanic', 'police' },
        ['account'] = 'bank',      -- Set your ['account']here
       --  ['requiredGrade']  = 3,
       --  ['requiredGang']  = { 'mechanic', 'police' },
   },
    ['police']  = {
        ['label'] = 'Armory',
        ['coords']  = vector4(-1864.43, -326.34, 44.01, 225.42),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(-1856.11, -318.13, 49.15, 349.6),
        ['requiredJob']  = 'police', -- Example: { 'mechanic', 'police' },
        ['account'] = 'bank',      -- Set your ['account']here
       --  ['requiredGrade']  = 3,
       --  ['requiredGang']  = { 'mechanic', 'police' },
   },
   ['police2']  = {
        ['label'] = 'Armory',
        ['coords']  = vector4(461.62, -981.08, 30.69, 85),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(-1856.11, -318.13, 49.15, 349.6),
        ['requiredJob']  = 'police', -- Example: { 'mechanic', 'police' },
        ['account'] = 'bank',      -- Set your ['account']here
       --  ['requiredGrade']  = 3,
       --  ['requiredGang']  = { 'mechanic', 'police' },
   },
    ['ambulance']  = {
        ['label'] = 'Medic Shop',
        ['coords']  = vector4(306.84, -601.53, 43.28, 338),
        ['ped'] = 's_m_m_doctor_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(-495.8, -335.52, 34.5, 237.64),
        ['requiredJob']  = 'ambulance', -- Example: { 'mechanic', 'police' },
        ['account'] = 'bank',         -- Set your ['account']here
    --  ['requiredGrade']  = 3,
    --  ['requiredGang']  = { 'mechanic', 'police' },
    },
    ['prison']  = {
        ['label'] = 'Canteen Shop',
        ['coords']  = vector4(1777.59, 2560.52, 44.62, 187.83),
        ['ped'] = false,
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577),
        ['account'] = 'bank', -- Set your ['account']here
       --  ['requiredJob']  = { 'mechanic', 'police' },
       --  ['requiredGrade']  = 3,
       --  ['requiredGang']  = { 'mechanic', 'police' },
   },
    -- Wedding Rings
    ['weddingrings']  = {
        ['label'] = 'weddingrings',
        ['coords']  = vector4(-633.57, -235.31, 37.99, 109.38),
        ['ped'] = 'cs_milton',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Jeweler',
        ['products'] = Config.Products['weddingrings'],
        ['showblip'] = false,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-636.76, -241.31, 38.11, 121.6),
        ['account'] = 'bank', -- Set your ['account']here
       --  ['requiredJob']  = { 'mechanic', 'police' },
       --  ['requiredGrade']  = 3,
       --  ['requiredGang']  = { 'mechanic', 'police' },
   },
       ['medshop']  = {
        ['label'] = 'Medical Supplies',
        ['coords']  = vector4(-663.04, 321.55, 83.08, 179),
        ['ped'] = 's_m_m_scientist_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Medical Shop',
        ['products'] = Config.Products['medshop'],
        ['showblip'] = false,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-663.04, 321.55, 83.08, 179),
        ['account'] = 'bank', -- Set your ['account']here
       --  ['requiredJob']  = { 'mechanic', 'police' },
       --  ['requiredGrade']  = 3,
       --  ['requiredGang']  = { 'mechanic', 'police' },
   },
}
