Citizen.CreateThread(function()
	AddTextEntry("WT_POCKETLIGHT", "Pocket Flashlight")
	AddTextEntry("WTD_POCKETLIGHT", "Small flashlight. As easy to conceal in your pocket, as it is easy to bust someone's car window open with it.")
	AddTextEntry("WTT_POCKETLIGHT", "The Pocket Flashlight")
	AddTextEntry("WTU_POCKETLIGHT", "POCKET FLASHLIGHT")
	AddTextEntry("WCT_PFLASH", "White Light")
	AddTextEntry("WCD_PFLASH", "Powerful white LED. Can light up 8 meters ahead with up to 10 hours battery life.")
	AddTextEntry("WCT_PFLASH_UV", "UV Light")
	AddTextEntry("WCD_PFLASH_UV", "A diode that emits light closer to ultraviolet spectrum. For revealing secrets, reading concealed letters, or making precise suntan.")
	AddTextEntry("WCT_PFLASH_RED", "Redlight")
	AddTextEntry("WCD_PFLASH_RED", "Scientists say eyes adapt quicker for the red color, and dim bloody light beam is much less noticeable from distance, making this filter ideal for those who doesn't want to be seen.")
	AddTextEntry("WCT_PFLASH_PSD", "Pocket-sized fleshlight")
	AddTextEntry("WCD_PFLASH_WAND", "*insert fallic joke here*")
	AddTextEntry("WCT_PFLASH_WAND_A", "Amber Wand")
	AddTextEntry("WCT_PFLASH_WAND_G", "Green Wand")
	AddTextEntry("WCT_PFLASH_WAND_R", "Red Wand")
	AddTextEntry("WCT_PFLASH_WAND_W", "White Wand")
end)