PrisonSchedulesConfig = {}

PrisonSchedulesConfig.NotifyTimes = 10000  --MS

if Config.MLOSelection == 'prompt-prison' then
    PrisonSchedulesConfig.Schedules = {
        ["min"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.work },
            { time = "10:00", State = Config.Lang.prison_schedule.work },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.work },
            { time = "14:00", State = Config.Lang.prison_schedule.work },
            { time = "15:00", State = Config.Lang.prison_schedule.work },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.shower },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["med"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.work },
            { time = "10:00", State = Config.Lang.prison_schedule.work },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.work },
            { time = "14:00", State = Config.Lang.prison_schedule.work },
            { time = "15:00", State = Config.Lang.prison_schedule.work },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.shower },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["max"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.work },
            { time = "10:00", State = Config.Lang.prison_schedule.work },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.work },
            { time = "14:00", State = Config.Lang.prison_schedule.work },
            { time = "15:00", State = Config.Lang.prison_schedule.work },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.shower },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["solitary"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.solitary },
            { time = "07:00", State = Config.Lang.prison_schedule.solitary },
            { time = "08:00", State = Config.Lang.prison_schedule.solitary },
            { time = "09:00", State = Config.Lang.prison_schedule.solitary },
            { time = "10:00", State = Config.Lang.prison_schedule.solitary },
            { time = "11:00", State = Config.Lang.prison_schedule.solitary },
            { time = "12:00", State = Config.Lang.prison_schedule.solitary },
            { time = "13:00", State = Config.Lang.prison_schedule.solitary },
            { time = "14:00", State = Config.Lang.prison_schedule.solitary },
            { time = "15:00", State = Config.Lang.prison_schedule.solitary },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.solitary },
            { time = "19:00", State = Config.Lang.prison_schedule.solitary },
            { time = "20:00", State = Config.Lang.prison_schedule.solitary },
            { time = "21:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "22:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        }
    }
    PrisonSchedulesConfig.Zones = { -- DO NOT ADD ANY NEW ZONES, ONLY EDIT THE EXISTING ONES COORDS AND SIZE DONT CHANGE THE NAME
    {
        coords = vector4(1612.63, 2476.03, 45.65, 139.22),
        size = { x = 55.0, y = 30.0, z = 10.0 },
        name = "Min Cell Block" -- Prisoners Should Be Here If they are in Min Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1612.02, 2497.21, 45.65, 321.21),
        size = { x = 3.0, y = 2.0, z = 4.0 },
        name = "Min Shower" -- Prisoners Should Be Here If they are in Min Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1692.43, 2448.71, 45.65, 179.48),
        size = { x = 55.0, y = 30.0, z = 10.0 },
        name = "Med Cell Block" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1678.0, 2466.0, 46.0, 0.00),
        size = { x = 3.0, y = 2.0, z = 4.0 },
        name = "Med Shower" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1764.3, 2483.68, 45.65, 209.41),
        size = { x = 55.0, y = 30.0, z = 10.0 },
        name = "Max Cell Block" -- Prisoners Should Be Here If they are in Max Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1743.49, 2491.3, 45.65, 29.27),
        size = { x = 3.0, y = 2.0, z = 4.0 },
        name = "Max Shower" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vec4(1736.7, 2576.5, 45.0, 0.0),
        size = vec3(24.85, 22.0, 14.05),
        name = "Cafeteria" --Prisoners Should Be Here If its Breakfast, Lunch or Dinner Time
    },
    {
        coords = vec4(1582.0, 2549.0, 45.0, 90.0),
        size = vec3(32, 30.0, 8.0),
        name = "Work" --Prisoners Should Be Here If its Work Time
    },
    {
        coords = vector4(1691.39, 2524.78, 45.56, 0.0),
        size = vec3(180, 80, 10),
        name = "Yard" --Prisoners Should Be Here If its Work Time
    },
    }
elseif Config.MLOSelection == 'molo-alcatraz' then
    PrisonSchedulesConfig.Schedules = {
        ["min"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.work },
            { time = "10:00", State = Config.Lang.prison_schedule.work },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.work },
            { time = "14:00", State = Config.Lang.prison_schedule.work },
            { time = "15:00", State = Config.Lang.prison_schedule.work },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.shower },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["med"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.work },
            { time = "10:00", State = Config.Lang.prison_schedule.work },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.work },
            { time = "14:00", State = Config.Lang.prison_schedule.work },
            { time = "15:00", State = Config.Lang.prison_schedule.work },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.shower },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["max"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.work },
            { time = "10:00", State = Config.Lang.prison_schedule.work },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.work },
            { time = "14:00", State = Config.Lang.prison_schedule.work },
            { time = "15:00", State = Config.Lang.prison_schedule.work },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.shower },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["solitary"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.solitary },
            { time = "07:00", State = Config.Lang.prison_schedule.solitary },
            { time = "08:00", State = Config.Lang.prison_schedule.solitary },
            { time = "09:00", State = Config.Lang.prison_schedule.solitary },
            { time = "10:00", State = Config.Lang.prison_schedule.solitary },
            { time = "11:00", State = Config.Lang.prison_schedule.solitary },
            { time = "12:00", State = Config.Lang.prison_schedule.solitary },
            { time = "13:00", State = Config.Lang.prison_schedule.solitary },
            { time = "14:00", State = Config.Lang.prison_schedule.solitary },
            { time = "15:00", State = Config.Lang.prison_schedule.solitary },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.solitary },
            { time = "19:00", State = Config.Lang.prison_schedule.solitary },
            { time = "20:00", State = Config.Lang.prison_schedule.solitary },
            { time = "21:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "22:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        }
    }
    PrisonSchedulesConfig.Zones = { -- DO NOT ADD ANY NEW ZONES, ONLY EDIT THE EXISTING ONES COORDS AND SIZE DONT CHANGE THE NAME
    {
        coords = vector4(3894.84, 26.5, 23.89, 84.05),
        size = { x = 10.0, y = 30.0, z = 10.0 },
        name = "Min Cell Block" -- Prisoners Should Be Here If they are in Min Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(3910.92, 38.35, 23.89, 83.05),
        size = { x = 3.0, y = 2.0, z = 4.0 },
        name = "Min Shower" -- Prisoners Should Be Here If they are in Min Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(3894.84, 26.5, 23.89, 84.05),
        size = { x = 10.0, y = 30.0, z = 10.0 },
        name = "Med Cell Block" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(3910.92, 38.35, 23.89, 83.05),
        size = { x = 3.0, y = 2.0, z = 4.0 },
        name = "Med Shower" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(3894.84, 26.5, 23.89, 84.05),
        size = { x = 10.0, y = 30.0, z = 10.0 },
        name = "Max Cell Block" -- Prisoners Should Be Here If they are in Max Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(3910.92, 38.35, 23.89, 83.05),
        size = { x = 3.0, y = 2.0, z = 4.0 },
        name = "Max Shower" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(3926.69, 29.26, 23.89, 263.78),
        size = vec3(20.0, 10.0, 10.0),
        name = "Cafeteria" --Prisoners Should Be Here If its Breakfast, Lunch or Dinner Time
    },
    {
        coords = vector3(4002.44, 59.84, 12.3),
        size = vec3(40.0, 10.0, 1.0),
        name = "Work1" --Prisoners Should Be Here If its Work Time
    },
    {
        coords = vector3(4070.29, 53.69, 18.79),
        size = vec3(20.0, 15.0, 5.0),
        name = "Work2" --Prisoners Should Be Here If its Work Time
    },
    {
        coords = vector3(4019.76, 25.28, 22.05),
        size = vec3(40.0, 25.0, 10.0),
        name = "Work3" --Prisoners Should Be Here If its Work Time
    },
    {
        coords = vector4(3966.2, 44.95, 22.34, 173.25),
        size = vec3(55, 25, 10),
        name = "Yard" --Prisoners Should Be Here If its Work Time
    },
}

elseif Config.MLOSelection == 'gabz-prison' then
    PrisonSchedulesConfig.Schedules = {
        ["min"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.free_time },
            { time = "10:00", State = Config.Lang.prison_schedule.free_time },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.free_time },
            { time = "14:00", State = Config.Lang.prison_schedule.free_time },
            { time = "15:00", State = Config.Lang.prison_schedule.free_time },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.free_time },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["med"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.free_time },
            { time = "10:00", State = Config.Lang.prison_schedule.free_time },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.free_time },
            { time = "14:00", State = Config.Lang.prison_schedule.free_time },
            { time = "15:00", State = Config.Lang.prison_schedule.free_time },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.free_time },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["max"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.rollcall },
            { time = "07:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "08:00", State = Config.Lang.prison_schedule.breakfast },
            { time = "09:00", State = Config.Lang.prison_schedule.free_time },
            { time = "10:00", State = Config.Lang.prison_schedule.free_time },
            { time = "11:00", State = Config.Lang.prison_schedule.lunch },
            { time = "12:00", State = Config.Lang.prison_schedule.lunch },
            { time = "13:00", State = Config.Lang.prison_schedule.free_time },
            { time = "14:00", State = Config.Lang.prison_schedule.free_time },
            { time = "15:00", State = Config.Lang.prison_schedule.free_time },
            { time = "16:00", State = Config.Lang.prison_schedule.yard },
            { time = "17:00", State = Config.Lang.prison_schedule.yard },
            { time = "18:00", State = Config.Lang.prison_schedule.dinner },
            { time = "19:00", State = Config.Lang.prison_schedule.dinner },
            { time = "20:00", State = Config.Lang.prison_schedule.free_time },
            { time = "21:00", State = Config.Lang.prison_schedule.free_time },
            { time = "22:00", State = Config.Lang.prison_schedule.free_time },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        },
        ["solitary"] = {
            { time = "00:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "01:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "02:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "03:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "04:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "05:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "06:00", State = Config.Lang.prison_schedule.solitary },
            { time = "07:00", State = Config.Lang.prison_schedule.solitary },
            { time = "08:00", State = Config.Lang.prison_schedule.solitary },
            { time = "09:00", State = Config.Lang.prison_schedule.solitary },
            { time = "10:00", State = Config.Lang.prison_schedule.solitary },
            { time = "11:00", State = Config.Lang.prison_schedule.solitary },
            { time = "12:00", State = Config.Lang.prison_schedule.solitary },
            { time = "13:00", State = Config.Lang.prison_schedule.solitary },
            { time = "14:00", State = Config.Lang.prison_schedule.solitary },
            { time = "15:00", State = Config.Lang.prison_schedule.solitary },
            { time = "16:00", State = Config.Lang.prison_schedule.solitary },
            { time = "17:00", State = Config.Lang.prison_schedule.solitary },
            { time = "18:00", State = Config.Lang.prison_schedule.solitary },
            { time = "19:00", State = Config.Lang.prison_schedule.solitary },
            { time = "20:00", State = Config.Lang.prison_schedule.solitary },
            { time = "21:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "22:00", State = Config.Lang.prison_schedule.lights_out },
            { time = "23:00", State = Config.Lang.prison_schedule.lights_out },
        }
    }
    PrisonSchedulesConfig.Zones = { -- DO NOT ADD ANY NEW ZONES, ONLY EDIT THE EXISTING ONES COORDS AND SIZE DONT CHANGE THE NAME
    {
        coords = vector4(1763.03, 2486.62, 46.56, 208.74),
        size = { x = 40.0, y = 20.0, z = 20.0 },
        name = "Min Cell Block" -- Prisoners Should Be Here If they are in Min Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1763.03, 2486.62, 46.56, 208.74),
        size = { x = 40.0, y = 20.0, z = 10.0 },
        name = "Med Cell Block" -- Prisoners Should Be Here If they are in Med Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1763.03, 2486.62, 46.56, 208.74),
        size = { x = 40.0, y = 20.0, z = 10.0 },
        name = "Max Cell Block" -- Prisoners Should Be Here If they are in Max Security, and if its Lights Out or Rollcall this is mandatory
    },
    {
        coords = vector4(1784.32, 2552.52, 45.67, 358.39),
        size = vec3(15.0, 15.0, 10.0),
        name = "Cafeteria" --Prisoners Should Be Here If its Breakfast, Lunch or Dinner Time
    },
    {
        coords = vector4(1691.39, 2524.78, 45.56, 0.0),
        size = vec3(180, 80, 10),
        name = "Yard" --Prisoners Should Be Here If its Work Time
    },
    }
elseif Config.MLOSelection == 'custom' then
    -- Open a Ticket So I can help you with your custom prison
end
